### PR TITLE
Flags

### PR DESCRIPTION
**Pull request by replaceitem**

### CODE REVIEW

**Comment by Ghoulboy78** [comment]
wait a sec mare, im still working on the biomes and entity thing

**Comment by replaceitem** [comment]
oh yeah, but i thought would be better to merge as often as possible before it gets too messy sry
then just merge when youre done

**Comment by Ghoulboy78** [comment]
thanks

**Review by Ghoulboy78 — APPROVED** [review]
I think it's good, lemme just check on the entity thing to see if it works or not

**Comment by replaceitem** [comment]
Nice, well done, thanks
Can be merged

**Pull request merged**
