### PR TITLE
Name change from World edit to scarpet edit

### PR DESCRIPTION
**Pull request by Ghoulboy78**
Closes #47 
Also helps disassociate from regular WE mod, to avoid possible problems.

### CODE REVIEW

**Comment by Firigion** [comment]
Looks good. I'll test it soon, but I don't expect it to break much. Either that, or break catastrophically.

**Comment by Ghoulboy78** [comment]
ok, it appears to work fine now.

**Comment by Firigion** [comment]
I crash when I load the world with the app. I had the same happen to me when developing some other thing, it happened when the command system was badly defined, somehow. Running latest carpet and fabric.

**Comment by Firigion** [comment]
It was a broken softlink from the namechange. I'll leave this here in case the same happens to someone else. Works fine!

**Review by Firigion — COMMENTED** [review]
Nice!

**Review by Firigion — APPROVED** [review]
Woops need to do an approve review.

**Pull request merged**
