### PR TITLE
Add a fancy help menu

### PR DESCRIPTION
**Pull request by altrisi**
Adds a help menu to the app. Fixes 3rd checkbox of #4.

The pagination buttons on the bottom are clickable.
You can click the command to get it as a suggestion in chat.
The description can have a tooltip and an action when clicked (suggest/run).

~Check docs in a comment, but basically you build a new entry by adding a list to the `help_entries` list like the following:
`[visibleCommand, commandToSuggest, description, descriptionTooltip, descriptionAction]` (those really can be anything, but that is the format spec).
It looks like `[visibleCommand] -> [description]`~

Ok, so the new system looks like the following: In the list, you add the command for carpet (eg `'wand <wand>'`) as the first element. The second element is the interpretation for carpet (what will that do, basically the other side of the regular commands map), and then the next item is either `false` (to prevent it from appearing in help menu, for example, `help` can be hidden since `help [page]` is basically the same) or another list with the info for the help menu. Basically:
- `[command_for_carpet, interpretation_for_carpet, false]` (hidden from help menu)
- `[command_for_carpet, interpretation_for_carpet, [optional_arguments_since, description, description_tooltip, description_action]]`

`optional_arguments_since` is a number telling the first argument to convert from required to optional (`<arg>` to `[arg]`). If none, use `-1`. This is done for things like the help example.

The number of entries displayed matches exactly the number of lines in chat without having it open for better readability (this messes up when an entry is longer than 1 line, may fix it in another PR).

This PR (now) includes localization for `en_us` for almost all messages in the menu. The only missing is the header's `WorldEdit Help` and the footer's `Page [num]`, because it being too delicate with breaking format.

To do localization, it also adds a new function `_translate()`, which is the same as the old one but with arbitrary arguments. The old one is now called `_translate_internal()`, and has a null check at the bottom (returns null if key was null).

The reason the things below the comment aren't added to the help menu is because they were not in the docs here. They can be easily added later.

_Note: Tested only in latest Carpet commit_

### CODE REVIEW

**Comment by BisUmTo** [comment]
Is it possible to generate the in-game docs Pages automatically ? 🤔
It should be...

You might add to the 'commands' map a "description" function that links it to a translatable string and pass the needed arguments 🙃

**Comment by altrisi** [comment]
Wait, can you add arbitrary data to the command map? How/were would you do it?

**Comment by BisUmTo** [comment]
global_commands_map = {...};

__config() -> {'commands'->global_commands_map}

**Comment by altrisi** [comment]
Wow, would never have thought about that, will do it in a bit.

**Comment by BisUmTo** [comment]
You should be able to create a run-time generated map with a not hardcoded keys and values 🤔...
That could compact the definition of commands...

**Comment by Ghoulboy78** [comment]
Not that im too fussy, but why some snake case and some camel case? rest of app uses snake case, so i would prefer it tbh...

**Comment by altrisi** [comment]
Oops, sorry, that's copy-pasted from that old notes app. Will fix it when pushing new system.

**Comment by gnembon** [comment]
Yeah - that's a good idea - to have commands defined outside and just generate them inside the config and use that info in the helper

**Comment by altrisi** [comment]
Well, it breaks entry order, but that part is done. Now missing: Translations.

**Comment by altrisi** [comment]
Well, it no longer breaks entry order, just changed the syntax again to not use maps. Now yes it gives the exact same behaviour.

Now missing for real: Translations.

**Comment by BisUmTo** [comment]
> Well, it no longer breaks entry order, just changed the syntax again to not use maps. Now yes it gives the exact same behaviour.
> 
> Now missing for real: Translations.

I'll work on it

**Comment by altrisi** [comment]
Oh, I already started moving things in local, should I stop?

**Comment by altrisi** [comment]
Well, I'll push it

**Comment by BisUmTo** [comment]
> Oh, I already started moving things in local, should I stop?

I recived only now notifications... LOL

**Comment by altrisi** [comment]
Ok, those two checkboxes are done (please check whether I ported translations correctly), and I fixed those merge conflicts.

**Comment by BisUmTo** [comment]
Why have some command description tralsations no formatting prefix?
🤔

**Comment by altrisi** [comment]
Oh, that's because at the begining I thought it would be a good idea to have every command description with the same color, I'll change it.

**Comment by altrisi** [comment]
Done, all descriptions now have their formatting attached, and also merged and fixed conflicts once again.

**Comment by altrisi** [comment]
Time to resolve conflicts again. Yay!

**Comment by altrisi** [comment]
Okay this time it was simple

**Review by Ghoulboy78 — APPROVED** [review]
Very good, now add the new command addition system to CONTRIBUTING.md

**Review by gnembon — APPROVED** [review]

**Comment by altrisi** [comment]
Added

**Comment by altrisi** [comment]
Please merge this or I'll end up closing it. It already has the 2 approvals, and I'm tired of merging conflicts (4th time already).

**Review by Ghoulboy78 — APPROVED** [review]
This looks good, imma merge and then resolve conflicts with my pr

**Pull request merged**
