### PR TITLE
Selection v2

### PR DESCRIPTION
**Pull request by gnembon**
better selection
 - we need some options to the menu - currently added quick-select - which allows to always draw a new selection
 - right click selects a marker (point) and allows to move it.
 - currently only for two corners, but adding extra corners is now possible.

### CODE REVIEW

**Comment by gnembon** [comment]
Maybe it shoud be more like mining - placing blocks, so left click picks the first corner, right click places the other, left click selects, right click sets back in

I just want to avoid accidental misclicks if left click is associated with an 'action' of any sorts, like placing points or applying brushes and transformations. (so you don't select by accident.

**Comment by Ghoulboy78** [comment]
well you see my only gripe with current selection system is this:
In regular WE, some operations (like filling) require both points, but some require only 1. Also
But thats isnt rly important tbh, u can set both points to the same spot to ahve selection size 1 block
I think you should add that you need to shift and left click to set first position (like brown carpets in distance command) so that accidentally mis clicking wont end up resetting all the selection.

**Comment by gnembon** [comment]
well - first position would only be set if there is no selection. If selection is made, you can't remove it without editing the points, so that's covered I guess.

**Comment by gnembon** [comment]
Other point is for ops that only require one point set - what are those operations?

**Comment by Ghoulboy78** [comment]
sphere ig

**Comment by gnembon** [comment]
ok, I misundestood the selection idea. I guess its just to highlight area for certain ops, not as a definite building area.

Will change that to be more temporary like, we style, but I still want to keep the points for some more advanced ops that require much more than 2 points.

**Comment by gnembon** [comment]
Ok - lets distinguish a few things. 
selection is a rectilinear area defined by two points. It can be used to highight things, or call some ops in that area (set, replace, stack etc.). We could have other types of selection, like the spherical selection later - that will be interesting.

Markers are points in space that you can define. Drawing a sphere requires one marker to be active as a center of the sphere. Drawing a sphere does not require a selection.

We might need a poppable menu that you can trigger with a compass or something to skip on using commands

**Comment by gnembon** [comment]
ok - for now the selection is we style by default (quick selection ,using left click to select from and riht click to select to), but the 'not-quick' selection is much better - can be adjusted.

**Pull request merged**
